title:               Franco’s Wikis
exclude:
  - '/_wikis/**/_drafts/*'
  - '*/obsidian.css'
  - '_wikis/templates/'
  - '/_wikis/_drafts/'

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  wikis:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_wikis/**/*.md"
    values:
      layout: "note"
